apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: workshop-manager
data:
  PORT: '3000'
  NODE_ENV: 'production'
  JWT_EXPIRES_IN: '3600s'
